language: go

go:
  - 1.8
  - 1.7
  - 1.6
  - master

install:
  - go get -u github.com/kardianos/govendor
  - go get github.com/mattn/goveralls
  - govendor sync

script:
  - goveralls -service=travis-ci
