language: go

go:
  - master
  - 1.9
  - 1.8

before_install:
  - go get -u github.com/kardianos/govendor
  - go get github.com/mattn/goveralls
  - govendor sync

script:
  - goveralls -service=travis-ci

after_success:
  - git checkout .
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
