# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/match.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/match.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11proto/match.proto\"\xba\x01\n\x05Match\x12\x0e\n\x06GameID\x18\x01 \x01(\x03\x12\x10\n\x08SeasonID\x18\x02 \x01(\x05\x12\x14\n\x0cGameCreation\x18\x03 \x01(\x03\x12\x14\n\x0cGameDuration\x18\x04 \x01(\x05\x12\"\n\x0cParticipants\x18\x05 \x03(\x0b\x32\x0c.Participant\x12\x0c\n\x04\x42\x61ns\x18\x06 \x03(\x03\x12\x10\n\x08GameMode\x18\x07 \x01(\t\x12\r\n\x05MapID\x18\x08 \x01(\x05\x12\x10\n\x08GameType\x18\t \x01(\t\"\x93\x01\n\x0bParticipant\x12\x14\n\x0cSummonerName\x18\x01 \x01(\t\x12\x11\n\tAccountID\x18\x02 \x01(\x03\x12\x13\n\x0bProfileIcon\x18\x03 \x01(\x05\x12\x12\n\nSummonerID\x18\x04 \x01(\x03\x12\x12\n\nChampionID\x18\x05 \x01(\x03\x12\x0e\n\x06TeamID\x18\x06 \x01(\x05\x12\x0e\n\x06Winner\x18\x07 \x01(\x08\x62\x06proto3')
)




_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GameID', full_name='Match.GameID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SeasonID', full_name='Match.SeasonID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameCreation', full_name='Match.GameCreation', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameDuration', full_name='Match.GameDuration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Participants', full_name='Match.Participants', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Bans', full_name='Match.Bans', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameMode', full_name='Match.GameMode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MapID', full_name='Match.MapID', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameType', full_name='Match.GameType', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=208,
)


_PARTICIPANT = _descriptor.Descriptor(
  name='Participant',
  full_name='Participant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SummonerName', full_name='Participant.SummonerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccountID', full_name='Participant.AccountID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ProfileIcon', full_name='Participant.ProfileIcon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SummonerID', full_name='Participant.SummonerID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChampionID', full_name='Participant.ChampionID', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TeamID', full_name='Participant.TeamID', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Winner', full_name='Participant.Winner', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=358,
)

_MATCH.fields_by_name['Participants'].message_type = _PARTICIPANT
DESCRIPTOR.message_types_by_name['Match'] = _MATCH
DESCRIPTOR.message_types_by_name['Participant'] = _PARTICIPANT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(
  DESCRIPTOR = _MATCH,
  __module__ = 'proto.match_pb2'
  # @@protoc_insertion_point(class_scope:Match)
  ))
_sym_db.RegisterMessage(Match)

Participant = _reflection.GeneratedProtocolMessageType('Participant', (_message.Message,), dict(
  DESCRIPTOR = _PARTICIPANT,
  __module__ = 'proto.match_pb2'
  # @@protoc_insertion_point(class_scope:Participant)
  ))
_sym_db.RegisterMessage(Participant)


# @@protoc_insertion_point(module_scope)
